
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    # No "depends_on" needed since DB is in the cloud

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    depends_on:
      - backend